# Icon
favicon: /favicon.ico
# SEO
keywords: Hexo, Gruntjs, Nodejs, Reactjs, Vuejs
# Header
page_background: /images/page_background.jpg
page_menu_button: dark
post_background: /images/post_background.jpg
post_menu_button: light
title_plancehold: 随笔
author:
  head: /images/logo.jpg
  signature: Only when you plant the flowers can you really smell their fragrance.
navication:
  - name: Github
    link: https://github.com
  - name: V2EX
    link: https://www.v2ex.com/
# content
content_width: 800
# Footer
## Social icon list: [facebook, twitter, weibo, wechat, github, stackoverflow, linkin, email, segmentfault, flickr, zhihu, disqus, douban, bilibili]
social:
  - name: Github
    icon: github
    link: https://github.com/
  - name: Weibo
    icon: weibo
    link: https://weibo.com/
  - name: SegmentFault
    icon: segmentfault
    link: https://www.segmentfault.com/
# Duoshuo
duoshuo:
  enable: true
  siteName: ueibo
# Copyright
copyright:
  record: false
  hexo: true
  laughing: true